services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - python_packages:/usr/local/lib/python3.10/site-packages
    ports:
      - 8000:8000
    env_file:
      - .env.local
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - .env.local
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  python_packages:
