# Generated by Django 4.2.14 on 2024-07-18 10:10

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.TextField()),
                ('formatted_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['address'], name='locations_l_address_632c0f_idx'), models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_c5d0f9_idx')],
            },
            managers=[
                ('maps', django.db.models.manager.Manager()),
            ],
        ),
    ]
